# Generated by Django 5.0.6 on 2024-05-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='sliders'),
        ),
    ]
