# Generated by Django 5.0.6 on 2024-05-15 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0002_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.TextField(null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
