# Generated by Django 5.0.6 on 2024-05-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0005_blogcategory_alter_aboutinfo_options_blog_blogimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
    ]
