# Generated by Django 5.0.6 on 2024-05-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0008_product_signs_video_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signs',
            new_name='Sign',
        ),
    ]
