# Generated by Django 5.0.6 on 2024-05-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0009_rename_signs_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=500)),
            ],
        ),
    ]
