# Generated by Django 5.0.6 on 2024-05-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0014_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimages',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='metaphysics.service'),
        ),
    ]
