# Generated by Django 5.0.6 on 2024-05-17 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0015_alter_serviceimages_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='metaphysics.blog'),
        ),
    ]
