# Generated by Django 5.0.6 on 2024-05-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphysics', '0016_remove_slider_link_alter_blogimages_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
